evancz/guide.elm-lang.org

architecture/effects/http.md, architecture/effects/time.md, architecture/user_input/forms.md, error_handling/README.md, error_handling/maybe.md, error_handling/result.md, interop/javascript.md, interop/json.md
I finished reading the guide and thought I'd submit a PR with some minor issues I came across.
=> Minor documentation fixes

interop/javascript.md
=> Minor grammar issue

architecture/effects/README.md
Just a quick typo fix. Thanks for the guide!
=> Minor typo fix, "lets" -> "let's"

architecture/effects/random.md
=> Fix tiny typo in random.md

book/webapps/structure.md
- Fixing misspellings
- Fixing broken links
=> Fix typo in webapps/structure

book/optimization/keyed.md
=> Fix typo in optimization/keyed.md

book/error_handling/README.md
- Fixing misspelling: alway -> always
=> spelling correction

book/appendix/types_as_sets.md
=> fix typo in Types as Sets

book/optimization/lazy.md
"each individual item changes" or "items change"
=> small typo fix in Lazy section

book/appendix/types_as_sets.md
- Fixing misspellings
- Fixing broken links
=> fix wrong link

book/interop/ports.md
- **Fixing misspellings**
- **Fixing broken links**
=> Fix Json.Encode.Value link

book/webapps/url_parsing.md
- Fixing misspellings
- Fixing broken links
=> Fix typo in `url_parsing.md`

book/optimization/lazy.md
=> Misspelling in the `lazy.md` file

book/optimization/lazy.md
=> Typo in the `lazy.md` file

book/core_language.md
This changes the syntax for the example to be valid
=> Add missing bracket

book/error_handling/README.md, book/interop/ports.md
1. Add highlighting to error handling code block
2. Add js instead of elm highlighting to javascript ports example
=> Add and change syntax highlighting in two code blocks

book/error_handling/maybe.md
the linked ellie app to convert celcius to farenheit does not compile.
=> Update the link to the Ellie example app

book/optimization/asset_size.md
=> uglifyjs doesn't support --ouput=elm.min.js notation

book/interop/README.md
Not 100% sure about this one, feel free to close.
=> Add possibly missing "we"

book/interop/README.md
I think this was a typo, but I'm not a native speaker.
=> Add missing "to"

book/error_handling/README.md
`Age 24` isn't a type. `Age Int` is.
=> Fix Typo in error_handling readme

book/error_handling/maybe.md
A singular possessive requires one
It's been a good read so far; cheers!
=> Fix missing apostrophe
