- error_handling/result.md
Minor typo fix:
"a int" => "an int"
> Another small typo fix

- architecture/modularity/counter_list.md
- error_handling/result.md
Minor typo fix:
"a abstraction barrier"  => "an abstraction barrier"
> Minor typo fix

- architecture/effects/http.md
Giphy has CORS enabled which means images will fail to load in at least Firefox. Simply making sure the URL uses https (good practice) fixes this example :)
See https://github.com/elm-lang/elm-lang.org/pull/612 for the same fix in the examples. It would be good to advocate https in the guide to set a good example.
> use https for GETting giphy url so example works in Firefox

- architecture/effects/http.md
The text referred to FetchSuccess, but the type is called FetchSucceed.
> Fix spelling mistake in http.md

- core_language.md
as python3 uses '/' for floating and '//' for integer, but in python2 this is not the case:
```
$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 9/2
4.5
>>> 9//2
4
```
```
$ python2
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 9/2
4
>>> 9.0/2
4.5
```
> changing guide core_language 'like python' to 'like python3'

- get_started.md
No file called `1-counter.elm` exists in the elm-architecture-tutorial repo.
> 1-counter.elm is not in elm-architecture-tutorial

- interop/json.md
The JSON section of the Interop chapter has several references to a nonexistent type `Decode`. This PR changes them to reference the `Decoder` type in the `Json.Decode` module.
> Fix references to Decoder

- architecture/user_input/text_fields.md
Removes an unnecessary String import form the example of the « Text Fields » section of the guide.
As [per documentation of the core module version 5.1.1](http://package.elm-lang.org/packages/elm-lang/core/5.1.1#default-imports), this module is part of the default imports.
> Remove unnecessary String import

- architecture/effects/http.md
In http://elm-lang.org/examples/http, the Json is imported like so:
```
import Json.Decode as Decode
```
But the [effects/http doc](https://guide.elm-lang.org/architecture/effects/http.html) calls `Json` (Json.Decoder, Json.at, ...) instead of `Decode`.
> Fix effects/http.md to make it consistent with http://elm-lang.org/examples/http

- core_language.md
A lot of beginners seem to trip over that first multiline function, because they don't know they need to add a whitespace before the second line.
> Add a note on indentation

- book/install.md
The old IntelliJ plugin has not been updated for over a year and does not support 0.19.
The new plugin is actively developed and supports both 0.18 and 0.19.
> Update link for IntelliJ plugin

- book/webapps/url_parsing.md
Fix typo in route example - `topic/scuplture` to `topic/sculpture` 👍
> Fix typo in route example - `topic/scuplture` to `topic/sculpture`

- book/optimization/keyed.md
The original code :
```elm
Keyed.node "ul" (List.map viewKeyedPresident presidents)
```
should be:
```elm
Keyed.node "ul" [] (List.map viewKeyedPresident presidents)
```
> fix missing square bracket in sample code for HTML.Keyed.node

- book/effects/http.md
Micro PR to fix #149 grammar issue in effects/http.md 
"In this example uses The Elm Architecture" > "This example uses The Elm Architecture" 
see: https://github.com/evancz/guide.elm-lang.org/issues/149
Thanks again for this _excellent_ guide! 👍
> Fix #149 Grammar Issue in effects/http.md 

- book/webapps/modules.md
In the example code of `modules.md` a function was named `decode` in the module exports, but `decoder` in the implementation.
> Fix typo in code of modules.md

- book/interop/README.md
- Fixing misspellings
- Fixing broken links
============================================
Noticed a typo in the interop section when I was going through the guide. This PR fixes the typo.
> Fixed typo in interop section

- book/effects/json.md
Fixed small typo "diferrence" => "difference".
> Fixed small typo

- book/optimization/asset_size.md
Quote `$@` to prevent re-splitting (SC2068)
Removed unnecessary `cat`s (SC2002)
> Edited optimize.sh based on shellcheck guidelines

- book/optimization/asset_size.md
Current code throws this error:
...```ERROR: `'pure_funcs=F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9,pure_getters,keep_fargs=false,unsafe_comps,unsafe'` is not a supported option
at DefaultsError.get```...
Code was fixed based on this link:
[uglify-js docs](https://www.npmjs.com/package/uglify-js#compress-options)
> Correction of code example to minify js output

- book/interop/flags.md
Letter case should not change when converting from JavaScript to Elm. 
P.S. Capitalized all names.
> Incorrect input in Interop / Flags
